CREATE DATABASE IF NOT EXISTS infinitwar CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE infinitwar;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(80) NOT NULL UNIQUE,
  nickname VARCHAR(32) NOT NULL,
  level INT UNSIGNED NOT NULL DEFAULT 1,
  vip_level TINYINT UNSIGNED NOT NULL DEFAULT 0,
  power BIGINT UNSIGNED NOT NULL DEFAULT 0,
  realm_id INT UNSIGNED NOT NULL DEFAULT 1,
  profile_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS heroes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  hero_code VARCHAR(48) NOT NULL,
  rarity VARCHAR(16) NOT NULL,
  level SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  stars TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ascension TINYINT UNSIGNED NOT NULL DEFAULT 0,
  shards_owned INT UNSIGNED NOT NULL DEFAULT 0,
  stats_json JSON NULL,
  skill_levels_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_heroes_user_code (user_id, hero_code),
  CONSTRAINT fk_heroes_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS buildings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  building_type VARCHAR(32) NOT NULL,
  slot_code VARCHAR(32) NOT NULL,
  level SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  state VARCHAR(16) NOT NULL DEFAULT 'IDLE',
  end_at_ms BIGINT UNSIGNED NOT NULL DEFAULT 0,
  task_id VARCHAR(80) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_buildings_user_slot (user_id, slot_code),
  CONSTRAINT fk_buildings_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS alliances (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  alliance_uid VARCHAR(80) NOT NULL UNIQUE,
  realm_id INT UNSIGNED NOT NULL DEFAULT 1,
  name VARCHAR(32) NOT NULL,
  tag VARCHAR(8) NOT NULL,
  leader_external_id VARCHAR(80) NOT NULL,
  member_count INT UNSIGNED NOT NULL DEFAULT 1,
  power BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS battles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  realm_id INT UNSIGNED NOT NULL DEFAULT 1,
  attacker_external_id VARCHAR(80) NOT NULL,
  defender_external_id VARCHAR(80) NOT NULL,
  battle_type VARCHAR(16) NOT NULL,
  result VARCHAR(16) NOT NULL,
  report_json JSON NULL,
  ended_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(80) NOT NULL,
  item_code VARCHAR(64) NOT NULL,
  quantity BIGINT UNSIGNED NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_inventory_owner_item (external_id, item_code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS receipts (
  receipt_id VARCHAR(64) NOT NULL PRIMARY KEY,
  external_id VARCHAR(80) NOT NULL,
  hero_id VARCHAR(64) NOT NULL,
  pack_id VARCHAR(64) NOT NULL,
  cost_gems INT UNSIGNED NOT NULL,
  issued_at_ms BIGINT UNSIGNED NOT NULL,
  signature VARCHAR(128) NOT NULL,
  used TINYINT(1) NOT NULL DEFAULT 0,
  used_at_ms BIGINT UNSIGNED NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_receipts_external (external_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS app_state (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  payload JSON NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;

INSERT IGNORE INTO app_state (id, payload) VALUES (1, JSON_OBJECT('users', JSON_OBJECT(), 'receipts', JSON_OBJECT(), 'alliances', JSON_OBJECT()));
